export {
  ITEM_CATEGORIES,
  buildEquipmentUniqueName,
  buildItemUniqueName,
  catalogItemMatchesFilters,
  compactSearchTerm,
  findCatalogItemByQuery,
  findCatalogItemByUniqueName,
  findCatalogItemsByQuery,
  getCatalogSearchText,
  getDisplayItemName,
  getDisplayItemTierLabel,
  getItemBaseDisplayName,
  getItemCatalog,
  getItemFamilyId,
  itemCatalog,
  loadItemCatalog,
  normalizeSearchTerm,
  resolveSelectedItemVariant,
  resolveItemVariation,
  searchItems,
} from '@/lib/itemSearch';
